# Site settings
title: 채영의 블로그
url: "http://gochaeyoung.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/Seoul
description: https://github.com/gochaeyoung/gochaeyoung.github.io/blob/master/media/KakaoTalk_20181112_131930118.jpg"
  description

# Your information
email: yunho0130@gmail.com
author: 고채영
# avatar: "https://github.com/gochaeyoung/gochaeyoung.github.io/blob/master/media/KakaoTalk_20181112_131930118.jpg"
avatar: "https://github.com/gochaeyoung/gochaeyoung.github.io/blob/master/media/KakaoTalk_20181112_131930118.jpg"
profile: <br> 영광 할렐루야 
#twitter_username: twitter_username
github_username:  gochaeyoung

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: maengdev   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-sitemap

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
