# Site settings
title: TO LOVE IS RECEIVE A GLIMPSE OF HEAVEN
url: "http://gochaeyoung.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "/" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/Seoul
description: >
  description

# Your information
email: gcy01110@naver.com
author: 고채영 경영학과 201610571 
# avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
avatar: "https://github.com/iris9190/iris9190.github.io/blob/master/media/smiling_face_466850.png"
profile: <br> 누구보다 행복한 날을 꿈꾸며 
#twitter_username: twitter_username
github_username:  gochaeyoung

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: maengdev   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

# Disqus
discuc-identifier : gochaeyoung.github.io # add your discus identifier

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-sitemap

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
